import type { Metadata } from "next";
import CraftsmanNavBar from "@/components/CraftsmanNavBar";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://procnova.jp"),
  title: "ProcNova Craftsman",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
    apple: "/icon.png",
  },
  openGraph: {
    images: [
      {
        url: "/ogpImage.png",
        width: 1200,
        height: 630,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/ogpImage.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="overflow-x-hidden antialiased">
        <div
          className="app-shell"
          style={{ paddingBottom: "var(--craftsman-nav-height)" }}
        >
          {children}
        </div>
        <CraftsmanNavBar />
      </body>
    </html>
  );
}
